# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"cwd": "03_workflow.ipynb",
         "save_notebooks_to": "03_workflow.ipynb"}

modules = ["data.py",
           "model.py",
           "loss.py",
           "workflow.py",
           "api.py"]

doc_url = "https://todowede.github.io/projectA/"

git_url = "https://github.com/todowede/projectA/tree/master/"

def custom_doc_links(name): return None
